add_library(q2psx_game STATIC
    ai.c
    ai.h
    aimove.c
    aimove.h
    aiworld.c
    aiworld.h
    effect.c
    effect.h
    events_rt.c
    events_rt.h
    explosive.c
    explosive.h
    flare.c
    flare.h
    hud.c
    hud.h
    aimodule.c
    aimodule.h
    combat.c
    combat.h
    creature.c
    creature.h
    crebind.c
    crebind.h
    cre_actions.c
    cre_arachner.c
    cre_berserk.c
    cre_gunner.c
    cre_infantry.c
    cre_insane.c
    cre_soldier.c
    cre_tankcomm.c
    cre_generic.c
    creworld.c
    creworld.h
    entity.c
    entity.h
    entitydraw.c
    entitydraw.h
    inventory.c
    inventory.h
    item.c
    item.h
    lighting.c
    lighting.h
    loading.c
    loading.h
    monster.c
    monster.h
    modeldraw.c
    modeldraw.h
    modelent.c
    modelent.h
    briefing.c
    briefing.h
    mission.c
    mission.h
    movie.c
    movie.h
    levelbin.c
    mover.c
    mover.h
    rotator.c
    rotator.h
    multiplayer.c
    multiplayer.h
    projectile.c
    projectile.h
    weapon.c
    weapon.h
    statusbar.c
    statusbar.h
    spawn.c
    spawn.h
    save.c
    save.h
    saveui.c
    saveui.h
    pad.c
    pad.h
    playerdeath.c
    playerdeath.h
    sim.c
    sim.h
    simcombat.c
    trace.c
    trace.h
    viewweapon.c
    viewweapon.h
    world.c
    world.h
)

target_include_directories(q2psx_game PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(q2psx_game PUBLIC
    q2psx_audio
    q2psx_common
    q2psx_build
    q2psx_disc
    q2psx_formats
    q2psx_menu
    q2psx_psx
)
